### PR TITLE
refactor: Content-type separtor use ';' instead of ','

### PR DESCRIPTION
**Pull request by toyah**
ref: https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @toyah!

**Comment by snewcomer** [comment]
@doomspork @jeregrine I have a feeling this PR might need to be reverted.  We separate multiple content-type or accept headers with a `,` and then use the `;` to separate the `type` and `parameter`.  As a result, the content_type_negotiation tests are failing on master.  I believe we already follow the spec:

From [Content-Type](https://www.w3.org/Protocols/rfc1341/4_Content-Type.html):
`type "/" subtype *[";" parameter]`

So we allow:
`application/vnd.api+json; version=1.0, application/vnd.api+json`

And then:

http://jsonapi.org/format/upcoming/#content-negotiation-clients

> Note: The content negotiation requirements exist to allow future versions of this specification to use media type parameters for extension negotiation and versioning.

**Comment by doomspork** [comment]
@snewcomer is it the change that's wrong or our content negotiation?  I'm pretty tied up this week so I won't have much time to dive into the spec but I'm confident in the decision you make so happy to defer to your judgement.

Thoughts @jeregrine?

**Comment by jeregrine** [comment]
I am happy to defer to @snewcomer's judgment

**Comment by snewcomer** [comment]
@toyah The link you put in the description is correct and we do use `;` to separate the type/subtype && the parameter.  The specific code this PR touched (the `,`) was to separate multiple media types, which the spec does provide leeway on.  So:

__Valid Content-Type/Accept header__

`application/vnd.api+json; version=1.0`
`application/vnd.api+json; version=1.0, application/vnd.api+json`

and we split on `,` to ensure that at least one of the media types has `application/vnd.api+json` in it.

Were you running into a specific error or perhaps do you see something I am not?

**Pull request merged**
