### PR TITLE
generate links with self on an index view

### PR DESCRIPTION
**Pull request by StareIntoTheBeard**

### CODE REVIEW

**Comment by jeregrine** [comment]
I plan on cutting a new release tomorrow evening!

**Comment by StareIntoTheBeard** [comment]
@jeregrine nice, looking forward to it.

**Comment by StareIntoTheBeard** [comment]
@jeregrine Hey there, any update on when to expect the new release?

**Comment by doomspork** [comment]
@StareIntoTheBeard any chance you can squash your commits?  I think you may need to rebase on master, there's a lot of duplicated commits

**Comment by jeregrine** [comment]
Once we squash this and merge it I will cut a release

**Pull request closed without merging**
