### PR TITLE
Prepare for 1.0

### PR DESCRIPTION
**Pull request by jherdman**

### CODE REVIEW

**Comment by jherdman** [comment]
Let's get #166 in first.

**Comment by jherdman** [comment]
@doomspork @snewcomer @jeregrine anything else we ought to sneak in for the major release?

**Comment by jherdman** [comment]
@doomspork IMHO, yes. I'll ping the author to see if there's still appetite to finish the PR. We can include that in a future release.

**Comment by doomspork** [comment]
@jherdman 1.0.0 is on hex. Could you please tag the release on GitHub? I need to step away for a bit. Thanks for all your hard work!

**Comment by jherdman** [comment]
On it! Many thanks ❤️

**Pull request merged**
