### PR TITLE
Code clean-up to satisfy Credo complaints

### PR DESCRIPTION
**Pull request by doomspork**
@jeregrine I was going through the code locally to clean up a few things and decided to run credo against the project which turned up a few more things I went ahead and cleaned up.  Let me know your thoughts, we can always close this PR too 😁 

If you'd like I can add a commit adding Credo, it's configuration, and a Travis hook.

### CODE REVIEW

**Comment by jeregrine** [comment]
@doomspork 👍 on adding credo

**Comment by doomspork** [comment]
I'll resolve the conflict, add Credo, and ping you for a second go round 😁

**Comment by doomspork** [comment]
This is good to go @jeregrine 👍

**Comment by doomspork** [comment]
Rebase and conflict free again!

**Comment by jeregrine** [comment]
Thank you! ❤️❤️

**Pull request merged**
