### PR TITLE
Run transform function only when the value is string or atom

### PR DESCRIPTION
**Pull request by aproxacs**
Found that it raises an error when the value is integer array. 
```
iex> alias JSONAPI.Utils.String, as: JString
iex> JString.expand_fields([12], &JString.camelize/1)
** (FunctionClauseError) no function clause matching in JSONAPI.Utils.String.camelize/1    
...
```

This PR is to fix this error by only running transform function when it is atom or string.

### CODE REVIEW

**Comment by doomspork** [comment]
@aproxacs could take a peek at whether it would be possible to add a test case of this change? It's be great to make sure we do re-introduce this issue down the road.

**Comment by aproxacs** [comment]
I resolved the conflicts and added test.

**Comment by lucacorti** [comment]
@doomspork I think this is googd to go too.

**Comment by d-staehler** [comment]
Could this please be released? Running into a similar issue and this change fixes it :)

**Comment by doomspork** [comment]
@jeregrine I'm going to be pretty busy for the next few days. Could you merge and release this?

**Comment by lucacorti** [comment]
@doomspork can we merge this?

**Review by jeregrine — APPROVED** [review]

**Comment by jeregrine** [comment]
> doomspork can we merge this?

Please do not do this. This is a volunteer effort.

**Pull request merged**
