### PR TITLE
Use Github Actions

### PR DESCRIPTION
**Pull request by jherdman**
Tests and Lints the project.

Note that I've not yet deleted the Travis config. I feel like that should be done once we're happy with this and decide to proceed with this approach.

Areas of Possible Improvement
--------------------------------

- Cache Dialyzer
- Cache deps
- Cache build
- Publishing upon tagging a release

### CODE REVIEW

**Comment by jherdman** [comment]
I'll open a "help wanted" ticket for that. It'd certainly be nice. It's relatively easy to do on services like Circle.

**Comment by lucacorti** [comment]
Hey guys, I've setup action cache for dialyzer for a few of my projects, it's quite straightforward, here is an excerpt from my job

```
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [21.3.8.13, 22.2.8]
        elixir: [1.9.4, 1.10.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
          restore-keys: |
             ${{ runner.os }}-${{ env.cache-name }}-
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
          restore-keys: |
             ${{ runner.os }}-${{ env.cache-name }}-
```

**Comment by jherdman** [comment]
@lucacorti would you be interested in opening a PR once this is merged so that you get appropriate credit?

**Comment by lucacorti** [comment]
@jherdman sure, no problem, or you can get it in and the credit too 😄

**Comment by jherdman** [comment]
@lucacorti merged! Feel free to open a PR whenever you have time.

**Comment by lucacorti** [comment]
@jherdman time is abundant right now, I live in italy, so I'm forced at home 😭 I've opened a PR, testing it right now.

**Pull request merged**
