### PR TITLE
Prepare for 1.2

### PR DESCRIPTION
**Pull request by jherdman**
It's time!

Is it possible to get release publishing rights with this release?

### CODE REVIEW

**Comment by doomspork** [comment]
@jherdman I don't believe I have hex permissions to add new releasers. I'll check later today.

**Comment by doomspork** [comment]
@jherdman is this good to merge and release now?

**Comment by jherdman** [comment]
Sure is!

**Comment by doomspork** [comment]
@jherdman is your hex username/email the same as the one listed on GitHub?

**Comment by jherdman** [comment]
@doomspork it's james.exe, and james.herdman@gmail.com.

**Comment by doomspork** [comment]
Awesome @jherdman, I'll add you now. I just published the release, could you tag it in GH?

**Comment by jherdman** [comment]
On it!

**Comment by doomspork** [comment]
Thank you. Added 😁

**Comment by jherdman** [comment]
Yayyyyy!!!

**Pull request merged**
